import {setupWorker} from 'msw/browser';
import {handlers} from './handlers';

/**
 * MSW browser service worker for Playwright E2E tests.
 *
 * The worker is registered from /mockServiceWorker.js (generated by `msw init public/`).
 *
 * To start the worker in a Playwright test:
 *
 *   await page.evaluate(async () => {
 *     const {worker} = await import('/app/test/msw/browser')
 *     await worker.start({onUnhandledRequest: 'bypass'})
 *   })
 *
 * Or use the shared Playwright fixture at tests/fixtures/msw.ts.
 */
export const worker = setupWorker(...handlers);
